# @name get_messages
GET http://localhost:3333/messages

###

# @name create_message
POST http://localhost:3333/messages
Content-Type: application/json

{
  "title": "vadia",
  "message": "hahahahahararararar"
}

###

# @name create_user
POST http://localhost:3333/user/register
Content-Type: application/json

{
  "name": "Willyam burron",
  "email": "willy@gmail.com",
  "password": "123"
}

###

# @name user_login
POST http://localhost:3333/user/login
Content-Type: application/json

{
  "email": "luis@gmail.com",
  "password": "123"
}
